### ISSUE TITLE
SlotRenderEndedEvent type is missing creativeTemplateId property

### ISSUE THREAD

**Issue by volodymyr-nd** [googleads/google-publisher-tag-types#1]
Both [GPT documentation](https://developers.google.com/publisher-tag/reference#googletag.events.slotrenderendedevent) and `@types/google-publisher-tags` don't mention that `SlotRenderEndedEvent` has `creativeTemplateId`, however this is not true. `creativeTemplateId` is part of the `event` from the event listener callback, and you can see it in the code example that I'm attaching below.

### Code example
I added a `slotRenderEnded` event listener on lines 67-69 which simply displays `creativeTemplateId` is present in the `event` object. If you open the console, you will see that it displays `"event object has creativeTemplateId: true"` as you scroll past the ads and they are rendered.
https://jsfiddle.net/2h85jzpL/12/

**Comment by jimper** [comment]
Hi @volodymyr-kl! Thanks for pointing this out, I'll check with the team and see what the status of that property is. There are occasionally API methods/properties that are purposely left undocumented (for example, if they're experimental or being sunset), but I'm not sure if this is one of those.

Do you have a particular use case in mind for this property? If so, could you share that with me so I can relay that to the team as well?

**Comment by jimper** [comment]
Hey @volodymyr-kl, the `creativeTemplateId` property along with a few others were added to the type defintions in b6107fa.  The updated version should already be available on npm. GPT documentation will be updated in the next day or so to match.

Thanks again for the report!
