### ISSUE TITLE
Status of setRequestNonPersonalizedAds method

### ISSUE THREAD

**Issue by volodymyr-nd** [googleads/google-publisher-tag-types#2]
Could you advise on the status of `setRequestNonPersonalizedAds`? I believe this is still an active method, and it's documented [here](https://support.google.com/admanager/answer/7678538?hl=en), however, I don't see this method in neither [GPT reference](https://developers.google.com/publisher-tag/reference) nor `@types/google-publisher-tags`.

**Comment by jimper** [comment]
The `setRequestNonPersonalizeAds` method is deprecated. It's still available in GPT for backwards compatibility reasons, but will eventually be removed. The [`PrivacySettingsConfig`](https://developers.google.com/publisher-tag/reference#googletag.privacysettingsconfig) API should be used to configure non-personalized ads moving forward. The [Configure privacy settings](https://developers.google.com/publisher-tag/samples/configure-privacy) sample has example usage.

Thanks for the pointer to the help center docs mentioning the old method. I'll work with the relevant product teams to have that updated.
